### ISSUE TITLE
Messing up with the issue board

### ISSUE THREAD

**Issue by mateus-amarante** [riuri/adventofcode#1]
What a rare notification:

![Screenshot from 2021-12-05 15-25-40](https://user-images.githubusercontent.com/7409263/144758750-e965f7a7-2ff1-4635-83b9-e1a21238a388.png)
 
Nice to hear from you :)

I hope you are doing well @riuri

**Comment by riuri** [comment]
Oi, Mateus!

Estou bem, e vc?

Realmente uma notificação rara, tô bem, mais ou menos bem com tendência de
melhora, mas detalhes só em comunicação privada 😄

E vc, como está?

Le dim. 5 déc. 2021 13 h 27, Mateus Amarante ***@***.***> a
écrit :

**Comment by mateus-amarante** [comment]
Estou bem também. Voltando pra Uberlandia em breve (detalhes no privado, hehehe).

Infelizmente (ou felizmente, não tenho certeza) o GitHub não tem opção de chat privado. Acho que não tenho seu telefone atual. Vou tentar lhe contactar por e-mail.

Abraço!
